# Generated by Django 4.2.26 on 2025-11-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('road-damage', 'Road Damage'), ('water-supply', 'Water Supply'), ('street-light', 'Street Light'), ('garbage', 'Garbage Collection'), ('drainage', 'Drainage'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('high', 'High - Urgent attention needed'), ('medium', 'Medium - Important but not urgent'), ('low', 'Low - Can be addressed later')], default='Medium', max_length=20),
        ),
    ]
