# Generated by Django 4.2.26 on 2025-11-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_complaint_category_alter_complaint_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('road-damage', 'Road Damage'), ('water-supply', 'Water Supply'), ('streetlight', 'Street Light'), ('garbage', 'Garbage Collection'), ('drainage', 'Drainage'), ('other', 'Other')], max_length=50),
        ),
    ]
